server:
  port: 4200

spring:
  application:
    name: jadyer-api-gateway

zuul:
  ignored-services: "*"
  routes:
    api-cal-url:
      path: /cal/**
      url: http://127.0.0.1:2100/
    api-add:
      path: /caladd/**
      serviceId: CalculatorServer
    CalculatorServer:
      path: /mycall/**
      #serviceId: CalculatorServer

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:1100/eureka/